name: Check Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup .NET
        uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852
        with:
          dotnet-version: "8.0.403"

      - name: Validate Code Snippets
        run: pwsh ./bin/check-code-snippets.ps1
